- defaults:
    link:
      create: true
      relink: true

- clean: ["~/.config/alacritty"]

- link:
    ~/.config/alacritty/alacritty.yml:
      path: alacritty/alacritty.yml

- shell:
    -
      command: sudo apt install -y alacritty
      description: Installing required Packages
      quiet: true
