- defaults:
    link:
      create: true
      relink: true

- clean: ["~"]

- link:
    ~/.bashrc:
      path: bash/.bashrc
    ~/.bash_aliases:
      path: bash/.bash_aliases
    ~/.bash_logout:
      path: bash/.bash_logout
