- link:
    ~/local/bin/mdtemp:
      path:local/bin/mdtemp/mdtemp
    ~/local/bin/textemp:
      path:local/bin/textemp/textemp
    ~/local/bin/tmux-rattacher:
      path:local/bin/tmux-reattacher
    ~/local/bin/set-monitors:
      path:local/bin/set-monitors
    ~/local/bin/set-set-screen-mirror:
      path:local/bin/set-screen-mirror
    ~/local/bin/set-volume:
      path:local/bin/set-volume
    ~/local/bin/cht-sh:
      path:local/bin/cht-sh
