- link:
    ~/.bin/mdtemp:
      path: bin/mdtemp/mdtemp
    ~/.bin/textemp:
      path: bin/textemp/textemp
    ~/.bin/tmux-rattacher:
      path: bin/tmux-reattacher
    ~/.bin/set-monitors:
      path: bin/set-monitors
    ~/.bin/set-set-screen-mirror:
      path: bin/set-screen-mirror
    ~/.bin/set-volume:
      path: bin/set-volume

- shell:
    -
      command: git submodule update --init --merge --remote bin/mdtemp bin/textemp
      description: Updating Submodules
      stderr: true
      stdout: true
