- link:
    ~/local/bin/mdtemp:
      path: bin/mdtemp/mdtemp
    ~/local/bin/textemp:
      path: bin/textemp/textemp
    ~/local/bin/tmux-rattacher:
      path: bin/tmux-reattacher
    ~/local/bin/set-monitors:
      path: bin/set-monitors
    ~/local/bin/set-set-screen-mirror:
      path: bin/set-screen-mirror
    ~/local/bin/set-volume:
      path: bin/set-volume
    ~/local/bin/set-brightness:
      path: bin/set-brightness
    ~/local/bin/cht-sh:
      path: bin/cht-sh
    ~/local/bin/get-mail:
      path: bin/get-mail
