- link:
    ~/.vimrc:
      path: vim/.min-vimrc
    ~/.zshrc:
      path: zsh/.zshrc
    ~/.tmux.conf:
      path: tmux/.tmux.conf
    ~/.gitconfig:
      path: git/.gitconfig
    ~/.zsh:
      path: zsh
    ~/.oh-my-zsh:
      path: zsh/ohmyzsh
    ~/.vim:
      path: vim
    ~/.config/git/.gitignore:
      path: git/.gitignore

- shell:
    -
      command: git submodule update --init --merge --remote zsh/ohmyzsh meta/dotbot
      description: Updating Submodules
      stderr: true
      stdout: true
    -
      command: sudo apt install -y vim zsh ncdu
      description: Installing required Packages
      quiet: true
    -
      command: test -d zsh/ohmyzsh/custom/plugins/zsh-autosuggestions && echo "zsh-autosuggestions exists" || git clone https://github.com/zsh-users/zsh-autosuggestions zsh/ohmyzsh/custom/plugins/zsh-autosuggestions
      description: Installing zsh autosuggestions
      stderr: true
      quiet: true
    -
      mkdir temp-inst && cd temp-inst && wget https://github.com/gokcehan/lf/releases/download/r22/lf-linux-amd64.tar.gz -O lf-linux-amd64.tar.gz && tar -xvf lf-linux-amd64.tar.gz && chmod +x lf && sudo mv lf /usr/local/bin ; cd .. ; rm -rf temp-inst
