- link:
    ~/.vimrc:
      path: vim/.vimrc
    ~/.zshrc:
      path: zsh/.zshrc
    ~/.tmux.conf:
      path: tmux/.tmux.conf
    ~/.gitconfig:
      path: git/.gitconfig
    ~/.zsh:
      path: zsh
    ~/.oh-my-zsh:
      path: zsh/ohmyzsh
    ~/.vim:
      path: vim
    ~/.local/share/konsole/blue_default.profile:
      path: konsole/blue_default.profile
    ~/.config/zathura/zathurarc:
      path: zathura/zathurarc
    ~/.config/polybar/config:
      path: polybar/config

- shell:
    - 
      command: git submodule update --remote --merge
      description: Updating Submodules
      stderr: true
      stdout: true
    - 
      command: vim -E -s -u ~/.vimrc +PluginInstall +qall
      description: Installing Vim plugins
      stderr: true
      stdout: true
    - 
      command: git clone https://github.com/zsh-users/zsh-autosuggestions ${ZSH_CUSTOM:-~/.oh-my-zsh/custom}/plugins/zsh-autosuggestions
      description: Installing zsh autosuggestions
      stderr: true
      stdout: true
      quiet: true
    - 
      command: sudo apt install -y apt-transport-https software-properties-common vim zsh ncdu tmux konsole zathura-pdf-poppler xdotool exuberant-ctags
      description: Installing required Packages
      quiet: true
      stderr: true
      stdout: true
    - 
      commmand: mkdir temp && cd temp && wget https://github.com/gokcehan/lf/releases/download/r22/lf-linux-amd64.tar.gz -O lf-linux-amd64.tar.gz && tar -xvf lf-linux-amd64.tar.gz && chmod +x lf && sudo mv lf /usr/local/bin ; cd .. ; rm -rf temp
      description: Installing lf terminal file manager
      quiet: true
      stderr: true
      stdout: true
