- defaults:
    link:
      create: true
      relink: true

- clean: ["~/.local/fonts"]

- link:
    ~/.local/fonts:
      path: fonts

- shell:
    -
      command: fc-cache -f -v
      description: Installing fonts
      sterr: true
      stdout: false
