- clean: ["~/.local/share/fonts"]

- link:
    ~/.local/share/fonts:
      path: fonts

- shell:
    -
      command: fc-cache -f -v
      description: Installing fonts
      sterr: true
      stdout: false
