- defaults:
    link:
      create: true
      relink: true

- clean: ["~"]

- link:
    ~/.gitconfig:
      path: git/.gitconfig
    ~/.config/git/.gitignore:
      path: git/.gitignore
    ~/.config/git/.gitattributes:
      path: git/.gitattributes
