- defaults:
    link:
      create: true
      relink: true
      force: true

- clean: ["~/.gnupg/"]

- link:
    ~/.gnupg/gpg-agent.conf:
      create: true
      force: true
      relink: true
      path: gnupg/gpg-agent.conf
