- defaults:
    link:
      create: true
      relink: true

- clean: ["~"]

- link:
  - ~/.config/lf/lfrc:
    path: lf/lfrc 

- shell:
    -
      mkdir temp-inst && cd temp-inst && wget https://github.com/gokcehan/lf/releases/download/r22/lf-linux-amd64.tar.gz -O lf-linux-amd64.tar.gz && tar -xvf lf-linux-amd64.tar.gz && chmod +x lf && sudo mv lf /usr/local/bin ; cd .. ; rm -rf temp-inst
