- link:
    ~/.bin/mdtemp:
      path: bin/mdtemp/mdtemp

- shell:
    -
      command: git submodule update --init --merge --remote bin/mdtemp
      description: Updating Submodules
      stderr: true
      stdout: true
