- link:
    ~/.config/nvim:
      path: nvim

- shell:
    -
      command: sh -c 'curl -fLo "${XDG_DATA_HOME:-$HOME/.local/share}"/nvim/site/autoload/plug.vim --create-dirs https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim'
      description: Setting up neovim
      sterr: true
      stdout: true
    -
      command: add-apt-repository ppa:neovim-ppa/unstable && apt update && apt install -y neovim ripgrep cargo
      description: Installing required Packages
      quiet: true
      stdout: true
    -
      command: npm i -g clangd bash-language-server cmake dockerfile-language-server-nodejs vscode-langservers-extracted pyright vim-language-server yaml-language-server
      description: Installing LSP servers
      stderr: true
      stdout: false
    -
      command: nvim --headless +COQdeps +q && nvim --headless +PlugInstall +q
      description: Installing nvim plugins
      stderr: true
    -
      command: nvim --headless +TSInstall cpp c bash python lua json latex regex yaml cmake bibtex dockerfile jsonc +q
      description: Installing nvim Treesitter language supports
      stderr: true
      stdout: true
    -
      command: cargo install --git https://github.com/latex-lsp/texlab.git --locked
      description: Installing texlab server
      stderr: true
      stdout: true
