- defaults:
    link:
      create: true
      relink: true

- clean: ["~/.config/polybar"]

- link:
    ~/.config/polybar/config:
      path: polybar/config

- shell:
    -
      command: sudo apt install -y polybar
      description: Installing required Packages
      quiet: true
