- link:
    ~/bin/textemp:
      path: bin/textemp

- shell:
    -
      command: git submodule update --init --merge --remote bin/textemp
      description: Updating Submodules
      stderr: true
      stdout: true
