- defaults:
    link:
      create: true
      relink: true

- clean: ["~"]

- link:
    ~/.tmux.conf:
      path: tmux/.tmux.conf

- shell:
    -
      command: sudo apt install -y tmux
      description: Installing required Packages
      quiet: true
