- defaults:
    link:
      create: true
      relink: true

- clean: ["~"]

- link:
  ~/.vimrc:
    path: vim/.min-vimrc
  ~/.vim:
    path: vim

- shell:
    -
      command: apt install -y vim
      description: Installing required Packages
      quiet: true
