link:
  ~/.vimrc:
      path: vim/.vimrc
  ~/.vim:
      path: vim

- shell:
    -
      command: git submodule update --init --merge --remote vim/bundle/Vundle.vim
      description: Updating Submodules
      sterr: true
      stdout: true
    -
      command: sudo apt install -y vim
      description: Installing required Packages
      quiet: true
    -
      command: vim -E -s -u ~/.vimrc +PluginInstall +qall
      description: Installing Vim plugins
      stderr: true
      stdout: true
    -
      command: mkdir -p ~/.vim/undodir
      description: Creating vim undodir
    -
      command: sudo apt install -y build-essential cmake python3-dev mono-complete golang nodejs default-jdk npm && cd ~/.vim/bundle/YouCompleteMe && python3 install.py --all
      description: Installing and Building YouCompleteMe
      sterr: true
      quite: true
