- link:
    ~/.config/Code/User/settings.json:
      path: vscode/settings.json
    ~/.config/Code/Dictionaries:
      path: vscode/Dictionaries
    ~/.config/Code/User/spellright.dict:
      path: vscode/spellright.dict
