language: shell

os: linux
dist: focal

git:
  depth: 1

branches:
  only:
    - master

addons:
  apt:
    update: true
    packages:
      - apt-transport-https
      - software-properties-common
      - vim
      - zsh
      - ncdu
      - tmux
      - alacritty
      - zathura-pdf-poppler
      - exuberant-ctags
      - fonts-powerline
      - ack-grep
      - build-essential
      - cmake
      - python3-dev
      - mono-complete
      - golang
      - nodejs
      - default-jdk
      - npm

script:
  - ./install-profile workstation
  - ./install-profile server
