language: shell

os: linux
dist: focal

git:
  depth: 1

addons:
  apt:
    update: true
    packages:
      - apt-transport-https
      - software-properties-common
      - vim
      - zsh
      - ncdu
      - tmux
      - konsole
      - zathura-pdf-poppler
      - exuberant-ctags

script:
  - ./install-profile default
  - ./install-profile container
  - ./install-profile full
