language: shell

os: linux
dist: focal

addons:
  apt:
    update: true
    packages:
      - apt-transport-https
      - software-properties-common
      - tar
      - vim
      - zsh
      - ncdu
      - tmux
      - konsole
      - zathura-pdf-poppler

script:
  - ./install
