language: shell

os: linux
dist: focal

addons:
  apt:
    update: true
    packages:
      - apt-transport-https
      - software-properties-common
      - vim
      - zsh
      - ncdu
      - tmux
      - konsole
      - zathura-pdf-poppler
      - exuberant-ctags

script:
  - ./install-profile base
  - ./install-profile full
