#!/usr/bin/env bash
BASEDIR=$(dirname $0)
cd $BASEDIR
zsh="zsh"

if [ !dpkg -s $zsh >/dev/null 2>&1 ]; then
    echo "Installing zsh"
    sudo apt install zsh
else
    echo "zsh already installed"
fi

git submodule init
git submodule update
ln -sf ${PWD}/.bashrc ~/.bashrc
ln -sf ${PWD}/.vimrc ~/.vimrc
ln -sf ${PWD}/.zshrc ~/.zshrc
ln -sf ${PWD}/git/.gitconfig ~/.gitconfig
if [ -e ~/.vim ]; then
    echo "~/.vim already exists"
else
    ln -s ${PWD}/.vim ~/.vim
fi
