#!/usr/bin/env bash
BASEDIR=$(dirname $0)
cd $BASEDIR
zsh="zsh"

if dpkg -s $pkg &>/dev/null
then
    echo "zsh already installed"
else
    echo "Installing zsh"
    sudo apt install zsh
fi

git submodule init
git submodule update
ln -sf ${PWD}/.bashrc ~/.bashrc
ln -sf ${PWD}/.vimrc ~/.vimrc
ln -sf ${PWD}/.zshrc ~/.zshrc
ln -sf ${PWD}/.gitconfig ~/.gitconfig
ln -sf ${PWD}/.vim ~/.vim

