#!/usr/bin/env bash
BASEDIR=$(dirname $0)
cd $BASEDIR

git submodule init
git submodule update
ln -sf ${PWD}/.bashrc ~/.bashrc
ln -sf ${PWD}/.vimrc ~/.vimrc
ln -sf ${PWD}/vgitconfig ~/.gitconfig
ln -sf ${PWD}/.vim ~/.vim

