- defaults:
    link:
      create: true
      relink: true
      force: true

- clean: ["~"]

- shell:
    -
      command: git submodule update --init --merge --remote meta/dotbot
      description: Updating Submodules
      stderr: true
      stdout: true