#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

# enable monitors if connected
$HOME/.bin/set-monitors &

bspc config border_radius        10
bspc config border_width         2
bspc config window_gap           18
bspc config top_padding          5
bspc config bottom_padding       0
bspc config left_padding         0
bspc config right_padding        0
bspc config automatic_scheme alternate
bspc config split_ratio          0.55
bspc config borderless_monocle   true
bspc config gapless_monocle      true
bspc config normal_border_color '#928374'
bspc config focused_border_color '#ebdbb2'
bspc config presel_border_color '#d79921'
bspc config normal_sticky_border_color '#4e4e4e'
bspc config focused_sticky_border_color '#83a598'
bspc config urgent_border_color '#fb4934'
bspc config click_to_focus any
bspc config pointer_follows_monitor	true
bspc config remove_disabled_monitors true
bspc config remove_unplugged_monitors true

# Application rules
bspc rule -a Zathura state=tiled
bspc rule -a Firefox state=tiled

# Wallpaper
feh --bg-scale $HOME/Pictures/Wallpapers/something.jpg &

# Start polybar
$HOME/dotfiles/polybar/launch.sh &

# Replace the cross cursor 
xsetroot -cursor_name left_ptr &
xset -dpms s off &
