#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

# enable monitors if connected
$HOME/.bin/set-monitors &

bspc config border_radius        10
bspc config border_width         2
bspc config window_gap           18
bspc config top_padding          45
bspc config bottom_padding       15
bspc config left_padding         30
bspc config right_padding        30
bspc config automatic_scheme alternate
bspc config split_ratio          0.55
bspc config borderless_monocle   false
bspc config gapless_monocle      false
bspc config normal_border_color '#928374'
bspc config focused_border_color '#ebdbb2'
bspc config presel_border_color '#d79921'
bspc config normal_sticky_border_color '#4e4e4e'
bspc config focused_sticky_border_color '#83a598'
bspc config urgent_border_color '#fb4934'
bspc config presel_feedback_color '#9cad68'
bspc config click_to_focus any
bspc config pointer_follows_monitor false
bspc config pointer_follows_focus false
bspc config remove_disabled_monitors true
bspc config remove_unplugged_monitors true

# Application rules
bspc rule -a Zathura state=tiled
bspc rule -a Firefox state=tiled
bspc rule -a Slack state=tiled desktop='^3'
bspc rule -a discord state=tiled desktop='^2'
bspc rule -a Zathura state=tiled follow=on focus=on desktop='^1'

# Wallpaper
feh --bg-scale $HOME/.config/wallpapers/something.jpg &

# Start polybar
$HOME/dotfiles/polybar/launch.sh &

# Replace the cross cursor 
xsetroot -cursor_name left_ptr &
xset -dpms s off &
xinput set-prop "Synaptics TM3418-002" "libinput Natural Scrolling Enabled" 1
